name: product-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - ipywidgets
  - jupyter_contrib_nbextensions
  - scikit-learn
  - lightgbm
  - SQLAlchemy
  - xgboost
  - seaborn
  - tqdm
  - openpyxl
  - time
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib